
include common.mk
MAKEFILE_SOURCES += glibc.mk

CFLAGS += -DHAVE_MREMAP=0 -D'LOCALEDIR=""' -D'GCONV_PATH=""' -D'GCONV_DIR=""' -D'LOCALE_ALIAS_PATH=""'

VPATH = 

SOURCES = \
  glibc/ctype/ctype-info.c \
  glibc/ctype/ctype.c \
  glibc/ctype/ctype_l.c \
  glibc/csu/dso_handle.c \
  glibc/debug/fortify_fail.c \
  glibc/debug/readonly-area.c \
  glibc/iconv/gconv.c \
  glibc/iconv/gconv_builtin.c \
  glibc/iconv/gconv_cache.c \
  glibc/iconv/gconv_close.c \
  glibc/iconv/gconv_conf.c \
  glibc/iconv/gconv_db.c \
  glibc/iconv/gconv_dl.c \
  glibc/iconv/gconv_open.c \
  glibc/iconv/gconv_simple.c \
  glibc/iconv/gconv_trans.c \
  glibc/io/mkdir.c \
  glibc/intl/dcgettext.c \
  glibc/intl/dcigettext.c \
  glibc/intl/explodename.c \
  glibc/intl/finddomain.c \
  glibc/intl/hash-string.c \
  glibc/intl/l10nflist.c \
  glibc/intl/loadmsgcat.c \
  glibc/intl/localealias.c \
  glibc/intl/plural.c \
  glibc/intl/plural-exp.c \
  glibc/io/access.c \
  glibc/io/close.c \
  glibc/io/fxstat.c \
  glibc/io/fxstat64.c \
  glibc/io/isatty.c \
  glibc/io/open.c \
  glibc/io/xstat.c \
  glibc/io/xstat64.c \
  glibc/libio/filedoalloc.c \
  glibc/libio/fileno.c \
  glibc/libio/fileops.c \
  glibc/libio/fputc.c \
  glibc/libio/fseek.c \
  glibc/libio/fseeko.c \
  glibc/libio/fseeko64.c \
  glibc/libio/ftello.c \
  glibc/libio/ftello64.c \
  glibc/libio/genops.c \
  glibc/libio/getc.c \
  glibc/libio/getc_u.c \
  glibc/libio/getchar.c \
  glibc/libio/getchar_u.c \
  glibc/libio/getwc.c \
  glibc/libio/getwc_u.c \
  glibc/libio/getwchar.c \
  glibc/libio/getwchar_u.c \
  glibc/libio/iofclose.c \
  glibc/libio/iofdopen.c \
  glibc/libio/iofgets.c \
  glibc/libio/iofflush.c \
  glibc/libio/iofopen.c \
  glibc/libio/iofopen64.c \
  glibc/libio/iofputs.c \
  glibc/libio/iofread.c \
  glibc/libio/iofwide.c \
  glibc/libio/iofwrite.c \
  glibc/libio/iogetdelim.c \
  glibc/libio/iogetline.c \
  glibc/libio/iopadn.c \
  glibc/libio/ioputs.c \
  glibc/libio/ioseekoff.c \
  glibc/libio/iosetvbuf.c \
  glibc/libio/ioungetc.c \
  glibc/libio/ioungetwc.c \
  glibc/libio/iovsprintf.c \
  glibc/libio/iovsscanf.c \
  glibc/libio/iowpadn.c \
  glibc/libio/putc.c \
  glibc/libio/putc_u.c \
  glibc/libio/putchar.c \
  glibc/libio/putchar_u.c \
  glibc/libio/putwc.c \
  glibc/libio/putwc_u.c \
  glibc/libio/putwchar.c \
  glibc/libio/putwchar_u.c \
  glibc/libio/stdfiles.c \
  glibc/libio/stdio.c \
  glibc/libio/strops.c \
  glibc/libio/vscanf.c \
  glibc/libio/vsnprintf.c \
  glibc/libio/wfiledoalloc.c \
  glibc/libio/wfileops.c \
  glibc/libio/wgenops.c \
  glibc/locale/C-address.c \
  glibc/locale/C-collate.c \
  glibc/locale/C-ctype.c \
  glibc/locale/C-identification.c \
  glibc/locale/C-measurement.c \
  glibc/locale/C-messages.c \
  glibc/locale/C-monetary.c \
  glibc/locale/C-name.c \
  glibc/locale/C-numeric.c \
  glibc/locale/C-paper.c \
  glibc/locale/C-telephone.c \
  glibc/locale/C-time.c \
  glibc/locale/C_name.c \
  glibc/locale/coll-lookup.c \
  glibc/locale/findlocale.c \
  glibc/locale/fpathconf.c \
  glibc/locale/global-locale.c \
  glibc/locale/lc-ctype.c \
  glibc/locale/loadarchive.c \
  glibc/locale/loadlocale.c \
  glibc/locale/localename.c \
  glibc/locale/mb_cur_max.c \
  glibc/locale/setlocale.c \
  glibc/locale/SYS_libc.c \
  glibc/locale/xlocale.c \
  glibc/malloc/malloc.c \
  glibc/malloc/morecore.c \
  glibc/misc/init-misc.c \
  glibc/misc/lseek.c \
  glibc/misc/mmap.c \
  glibc/misc/mmap64.c \
  glibc/misc/mprotect.c \
  glibc/misc/munmap.c \
  glibc/misc/sbrk.c \
  glibc/misc/tsearch.c \
  glibc/posix/confstr.c \
  glibc/posix/environ.c \
  glibc/posix/getegid.c \
  glibc/posix/geteuid.c \
  glibc/posix/getgid.c \
  glibc/posix/getuid.c \
  glibc/posix/regex.c \
  glibc/stdio-common/_itoa.c \
  glibc/stdio-common/fprintf.c \
  glibc/stdio-common/fxprintf.c \
  glibc/stdio-common/itoa-digits.c \
  glibc/stdio-common/itoa-udigits.c \
  glibc/stdio-common/itowa-digits.c \
  glibc/stdio-common/printf.c \
  glibc/stdio-common/printf_fp.c \
  glibc/stdio-common/printf_fphex.c \
  glibc/stdio-common/printf-parsemb.c \
  glibc/stdio-common/printf-parsewc.c \
  glibc/stdio-common/reg-modifier.c \
  glibc/stdio-common/reg-printf.c \
  glibc/stdio-common/reg-type.c \
  glibc/stdio-common/snprintf.c \
  glibc/stdio-common/sprintf.c \
  glibc/stdio-common/sscanf.c \
  glibc/stdio-common/vfprintf.c \
  glibc/stdio-common/vfscanf.c \
  glibc/stdio-common/vfwprintf.c \
  glibc/stdlib/add_n.c \
  glibc/stdlib/addmul_1.c \
  glibc/stdlib/bsearch.c \
  glibc/stdlib/cmp.c \
  glibc/stdlib/cxa_atexit.c \
  glibc/stdlib/divrem.c \
  glibc/stdlib/exit.c \
  glibc/stdlib/fpioconst.c \
  glibc/stdlib/getenv.c \
  glibc/stdlib/grouping.c \
  glibc/stdlib/lshift.c \
  glibc/stdlib/msort.c \
  glibc/stdlib/mul.c \
  glibc/stdlib/mul_1.c \
  glibc/stdlib/mul_n.c \
  glibc/stdlib/qsort.c \
  glibc/stdlib/rshift.c \
  glibc/stdlib/setenv.c \
  glibc/stdlib/strtod.c \
  glibc/stdlib/strtod_l.c \
  glibc/stdlib/strtof.c \
  glibc/stdlib/strtof_l.c \
  glibc/stdlib/strtold.c \
  glibc/stdlib/sub_n.c \
  glibc/stdlib/submul_1.c \
  glibc/stdlib/tens_in_limb.c \
  glibc/string/_strerror.c \
  glibc/string/argz-addsep.c \
  glibc/string/argz-append.c \
  glibc/string/argz-count.c \
  glibc/string/argz-create.c \
  glibc/string/argz-ctsep.c \
  glibc/string/argz-delete.c \
  glibc/string/argz-extract.c \
  glibc/string/argz-insert.c \
  glibc/string/argz-next.c \
  glibc/string/argz-replace.c \
  glibc/string/argz-stringify.c \
  glibc/string/bcopy.c \
  glibc/string/bzero.c \
  glibc/string/memccpy.c \
  glibc/string/memchr.c \
  glibc/string/memcmp.c \
  glibc/string/memcpy.c \
  glibc/string/memfrob.c \
  glibc/string/memmem.c \
  glibc/string/memmove.c \
  glibc/string/mempcpy.c \
  glibc/string/memrchr.c \
  glibc/string/memset.c \
  glibc/string/rawmemchr.c \
  glibc/string/stpcpy.c \
  glibc/string/stpncpy.c \
  glibc/string/strcasecmp.c \
  glibc/string/strcasecmp_l.c \
  glibc/string/strcasestr.c \
  glibc/string/strcat.c \
  glibc/string/strchr.c \
  glibc/string/strchrnul.c \
  glibc/string/strcmp.c \
  glibc/string/strcoll.c \
  glibc/string/strcoll_l.c \
  glibc/string/strcpy.c \
  glibc/string/strdup.c \
  glibc/string/strerror.c \
  glibc/string/strerror_l.c \
  glibc/string/strlen.c \
  glibc/string/strncase.c \
  glibc/string/strncase_l.c \
  glibc/string/strncat.c \
  glibc/string/strncmp.c \
  glibc/string/strncpy.c \
  glibc/string/strndup.c \
  glibc/string/strnlen.c \
  glibc/string/strrchr.c \
  glibc/string/strsep.c \
  glibc/string/strstr.c \
  glibc/string/strtok.c \
  glibc/string/strtok_r.c \
  glibc/string/strxfrm.c \
  glibc/string/strxfrm_l.c \
  glibc/string/swab.c \
  glibc/string/wordcopy.c \
  glibc/sysdeps/ieee754/dbl-64/word-64/s_isinf.c \
  glibc/sysdeps/ieee754/dbl-64/word-64/s_isnan.c \
  glibc/sysdeps/ieee754/dbl-64/dbl2mpn.c \
  glibc/sysdeps/ieee754/dbl-64/mpn2dbl.c \
  glibc/sysdeps/ieee754/flt-32/mpn2flt.c \
  glibc/sysdeps/ieee754/ldbl-64-128/strtold_l.c \
  glibc/sysdeps/ieee754/ldbl-128/ldbl2mpn.c \
  glibc/sysdeps/ieee754/ldbl-128/mpn2ldbl.c \
  glibc/sysdeps/ieee754/ldbl-128/s_isinfl.c \
  glibc/sysdeps/ieee754/ldbl-128/s_isnanl.c \
  glibc/sysdeps/llamaos/elf/enbl-secure.c \
  glibc/sysdeps/llamaos/elf/dl-libc.c \
  glibc/sysdeps/llamaos/elf/dl-profstub.c \
  glibc/sysdeps/llamaos/posix/_exit.c \
  glibc/sysdeps/llamaos/posix/sysconf.c \
  glibc/sysdeps/llamaos/abort.c \
  glibc/sysdeps/llamaos/assert.c \
  glibc/sysdeps/llamaos/brk.c \
  glibc/sysdeps/llamaos/errlist.c \
  glibc/sysdeps/llamaos/errno.c \
  glibc/sysdeps/llamaos/getcwd.c \
  glibc/sysdeps/llamaos/getpagesize.c \
  glibc/sysdeps/llamaos/init-first.c \
  glibc/sysdeps/llamaos/libc_fatal.c \
  glibc/sysdeps/llamaos/lseek64.c \
  glibc/sysdeps/llamaos/madvise.c \
  glibc/sysdeps/llamaos/pathconf.c \
  glibc/sysdeps/llamaos/poll.c \
  glibc/sysdeps/llamaos/read.c \
  glibc/sysdeps/llamaos/write.c \
  glibc/sysdeps/llamaos/writev.c \
  glibc/sysdeps/wordsize-64/strtol.c \
  glibc/sysdeps/wordsize-64/strtol_l.c \
  glibc/sysdeps/wordsize-64/strtoul.c \
  glibc/sysdeps/wordsize-64/strtoul_l.c \
  glibc/time/alt_digit.c \
  glibc/time/era.c \
  glibc/time/gettimeofday.c \
  glibc/time/lc-time-cleanup.c \
  glibc/time/localtime.c \
  glibc/time/mktime.c \
  glibc/time/offtime.c \
  glibc/time/strftime.c \
  glibc/time/strftime_l.c \
  glibc/time/tzfile.c \
  glibc/time/tzset.c \
  glibc/time/wcsftime.c \
  glibc/time/wcsftime_l.c \
  glibc/wcsmbs/btowc.c \
  glibc/wcsmbs/mbrlen.c \
  glibc/wcsmbs/mbrtowc.c \
  glibc/wcsmbs/mbsnrtowcs.c \
  glibc/wcsmbs/mbsrtowcs.c \
  glibc/wcsmbs/mbsrtowcs_l.c \
  glibc/wcsmbs/wcpcpy.c \
  glibc/wcsmbs/wcpncpy.c \
  glibc/wcsmbs/wcrtomb.c \
  glibc/wcsmbs/wcschr.c \
  glibc/wcsmbs/wcschrnul.c \
  glibc/wcsmbs/wcscmp.c \
  glibc/wcsmbs/wcscoll.c \
  glibc/wcsmbs/wcscoll_l.c \
  glibc/wcsmbs/wcslen.c \
  glibc/wcsmbs/wcsnlen.c \
  glibc/wcsmbs/wcsmbsload.c \
  glibc/wcsmbs/wcsrtombs.c \
  glibc/wcsmbs/wcsstr.c \
  glibc/wcsmbs/wcsxfrm.c \
  glibc/wcsmbs/wcsxfrm_l.c \
  glibc/wcsmbs/wctob.c \
  glibc/wcsmbs/wmemchr.c \
  glibc/wcsmbs/wmemcmp.c \
  glibc/wcsmbs/wmemcpy.c \
  glibc/wcsmbs/wmemmove.c \
  glibc/wcsmbs/wmempcpy.c \
  glibc/wcsmbs/wmemset.c \
  glibc/wctype/iswctype.c \
  glibc/wctype/towctrans.c \
  glibc/wctype/wcfuncs.c \
  glibc/wctype/wcfuncs_l.c \
  glibc/wctype/wctype.c \
  glibc/wctype/wctrans.c

BINARY  = glibc.a
OBJECTS = $(SOURCES:%.c=$(OBJDIR)/%.o)
DEPENDS = $(OBJECTS:%.o=%.d)

$(LIBDIR)/$(BINARY): $(OBJECTS)
	@[ -d $(@D) ] || (mkdir -p $(@D))
	@echo linking: $@
	@$(AR) r $@ $(OBJECTS)
	@echo successfully built: $@
	@echo

include rules.mk

# include auto-generated dependencies
ifneq ($(MAKECMDGOALS),clean)
-include $(DEPENDS)
endif
